workspace 'ETFrameworkDemo'
xcodeproj 'ETFrameworkDemo'
xcodeproj 'ETFrameworkTests/ETFrameworkTests'

target :ETFrameworkDemo do
    platform :ios, '5.0'
	pod 'AFNetworking', '~> 1.3.1', :inhibit_warnings => true
    xcodeproj 'ETFrameworkDemo'
end

target :ETFrameworkTests do
    platform :ios, '5.0'
    pod 'OCMock', '~> 2.2.1', :inhibit_warnings => true
    xcodeproj 'ETFrameworkTests/ETFrameworkTests'
end